# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tonyby/wordpress
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: Always

env:
  - name: WORDPRESS_DB_HOST
    value: 192.168.202.26
  - name: WORDPRESS_DB_USER
    value: wordpress
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress
  - name: WORDPRESS_DB_NAME
    value: wordpress_test 

service:
  #type: ClusterIP
  port: 80

ingress:
  enabled: enable
  className: ""
  annotations: 
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/server-alias: "wordpress.k8s-26.sa"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: wordpress.k8s-25.sa
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
    limits:
     cpu: 1000m
     memory: 512Mi
    requests:
     cpu: 500m
     memory: 128Mi

persistentVolume:
    storage: 5Gi


# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}
