name: Build push image and generate chart 
on:
  push:
    branches:
      - main
jobs:
  bump-ver-push-tag:
    name: Bump version and push tag 
    runs-on: ubuntu-latest
    outputs:
        tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout   
        uses: actions/checkout@v3
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "" 
      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}
  
  build-and-push-image:
    name: Build and push image 
    needs: bump-ver-push-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkecout
        uses: actions/checkout@v3
      
      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./wordpress
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wordpress:${{ needs.bump-ver-push-tag.outputs.tag }}
  
  # list-manifests:
  #   name: List manifests for validation  
  #   runs-on: ubuntu-latest
  #   outputs:
  #      matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - id: set-matrix
  #       run: echo "::set-output name=matrix::$(ls charts/wordpress/templates/*.yaml | jq -R -s -c 'split("\n")[:-1]')"
  # kubeval:
  #   name: Validate manifests
  #   needs: list-manifests
  #   runs-on: ubuntu-latest
  #   strategy:
  #        matrix:
  #            manifest: ${{ fromJson(needs.list-manifests.outputs.matrix) }}
  #   steps:
  #     - name: Ckeckout 
  #       uses: actions/checkout@v3     
  
  #     - name: Validate manifests by kubeval 
  #       uses: instrumenta/kubeval-action@master
  #       with:
  #         files: ${{ matrix.manifest }}       
  
  # generate-chart:
  #   name: Generate Chart
  #   needs: bump-ver-push-tag
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkecout
  #       uses: actions/checkout@v3
  #     # - name: Install Helm
  #     #   uses: Azure/setup-helm@v3
  #     #   with:    
  #     #     version: v3.10.0
  
  #     # - name: Helm package
  #     #   run: |
  #     #   helm package charts/wordpress --version ${{ needs.bump-ver-push-tag.outputs.tag }} --app-version ${{ needs.bump-ver-push-tag.outputs.tag }}

  #     - name: Update appVersion
  #       run: |
  #         sed -i "s/^version:.*$/version: ${{ needs.bump-ver-push-tag.outputs.tag }}/" ./charts/wordpress/Chart.yaml
  #         sed -i "s/^appVersion:.*$/appVersion: ${{ needs.bump-ver-push-tag.outputs.tag }}/" ./charts/wordpress/Chart.yaml

  #     - name: Commit changes
  #       run: |
  #         git config user.name "$GITHUB_ACTOR"
  #         git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
  #         git add .
  #         git commit -m "Update appVersion to ${{ needs.bump-ver-push-tag.outputs.tag }} by GitHub Actions"
  #         git push origin main
  
  lint-helm:
    name: Helm Lint
    needs: bump-ver-push-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Helm lint
        run: |
          helm lint ./charts/wordpress              
  
  chart-release:
    name: Chart release
    needs: [bump-ver-push-tag, lint-helm]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update appVersion
        run: |
          sed -i "s/^version:.*$/version: ${{ needs.bump-ver-push-tag.outputs.tag }}/" ./charts/wordpress/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: ${{ needs.bump-ver-push-tag.outputs.tag }}/" ./charts/wordpress/Chart.yaml

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: ./charts/wordpress
        env: 
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  
  slackNotification:
    name: Slack notofication
    needs: [bump-ver-push-tag, build-and-push-image, chart-release]
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
          SLACK_CHANNEL: notifications
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Release v${{ needs.bump-ver-push-tag.outputs.tag }} Status: ${{ job.status }} :rocket:'
          SLACK_TITLE: Chart Release
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
